### ISSUE TITLE
Cannot read property 'repo' of null

### ISSUE THREAD

**Issue by agarzola** [eanplatter/forked#2]
I’m getting this error after installing, navigating to a project dependency (on an unrelated project), and using `fork`:

```
/bin/sh: json: command not found
/usr/local/lib/node_modules/forked/dist/index.js:35
var index = meta.repo.indexOf('.git');
                ^

TypeError: Cannot read property 'repo' of null
    at Object.<anonymous> (/usr/local/lib/node_modules/forked/dist/index.js:35:17)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:136:18)
    at node.js:963:3
```

I also noticed that [line #33](https://github.com/eanplatter/forked/blob/master/dist/index.js#L33) seems to be missing something, which may be related. I haven’t used babel yet, though, so I might just be missing something here.

**Comment by eanplatter** [comment]
Looks like meta isn't being defined properly, what module were you trying to fork? I can probably reproduce it.

**Comment by agarzola** [comment]
[slush](https://github.com/slushjs/slush)

**Comment by eanplatter** [comment]
Thanks I'll check it out!

**Comment by eanplatter** [comment]
Hrmmm, it worked for me, but I did ship some bug fixes recently, what version of forked are you using?

EDIT:
Screen shot:
<img width="419" alt="screen shot 2016-04-05 at 8 27 24 pm" src="https://cloud.githubusercontent.com/assets/3782604/14303058/caca5b92-fb6c-11e5-8fec-afa1929415a1.png">

**Comment by agarzola** [comment]
`0.0.11` it looks like.

**Comment by agarzola** [comment]
I just tried it on `shelljs` with the same result. Something is clearly wrong on my end. I’m on node 4.2.2, if that makes a difference.

**Comment by eanplatter** [comment]
So the way it works is forked is looking for a `./package.json` file, I am able to reproduce your error by running `$ fork` in a random folder that doesn't contain a `package.json` file.

**Comment by agarzola** [comment]
![screenshot 2016-04-05 21 32 46](https://cloud.githubusercontent.com/assets/439649/14303135/0f677f38-fb76-11e5-9ea7-941b844b5f7e.png)

**Comment by agarzola** [comment]
I wonder what that `json: command not found` is all about.

**Comment by eanplatter** [comment]
hrmmm I think the crux of the error is actually the `/bin/sh: json: command not found`.

Looks like it's not able to run the parsing command, which explains why meta is undefined.

**Comment by eanplatter** [comment]
I might be wrongfully assuming environment specific things, looking into it

**Comment by agarzola** [comment]
Right. Does it make sense that package.json defines `dist/main.js` instead of `dist/index.js`?

**Comment by eanplatter** [comment]
Oh that's borked too, ima fix that.

Could you try running this in your console and show me what it spits out?
`$ cat package.json | json repository.url`

**Comment by agarzola** [comment]
`bash: json: command not found` Clearly I’m missing that.

**Comment by eanplatter** [comment]
Well, if you are then a lot of other people probably are.

**Comment by agarzola** [comment]
I got a PR for you in a sec.
